config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :stories
    end
  end

  root to: 'pages#home'
  devise_for :users, controllers: { sessions: 'sessions' }
  resources :users, only: %i[edit update destroy show index] do
    get 'invite', action: :user_invite
    get 'team', action: :team
  end
  devise_scope :user do
    post '/users/invitation/new', to: 'invitations#invite_resource', as: :new_invite
  end
  resources :stories
  resources :team_presentations
  get 'site_overview', to: 'stories#site_overview', as: :site_overview
  match '/search_suggestions', to: 'search_suggestions#index', via: :get
end

app/models/story.rb
class Story < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged history]
  default_scope { order(created_at: :desc) }
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy
  validates :title, presence: true

  scope :stories_author, ->(user) { where(user_id: user.id) }
  scope :search, ->(title) { where('title like ?', "%#{title}%") }

  def tag_list
    tags.join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/controllers/api/v1/stories_controller.rb
module Api
  module V1
    class StoriesController < ApplicationController
      before_action :restrict_access
      respond_to :json

      include StoriesHelper
      before_action :set_story, only: %i[show edit update destroy]
      before_action :authorize_actions, only: %i[edit update destroy]

      def index
        @stories = policy_scope(Story)
        @stories = @stories.search(params[:search]) if params[:search]
        respond_with @stories
      end

      def show
        respond_with @story
      end

      def create
        respond_with Story.create(story_params)
      end

      def update
        respond_with Story.update(story_params)
      end

      def destroy
        respond_with Story.destroy(@story)
      end

      private

      def set_story
        @story = Story.find(params[:id]).decorate
      end

      def authorize_actions
        authorize @story
      end

      def restrict_access
        authenticate_or_request_with_http_token do |token, _options|
          ApiKey.exists?(access_token: token)
        end
      end
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  include StoriesHelper
  before_action :set_story, only: %i[show edit update destroy]
  before_action :authorize_actions, only: %i[edit update destroy]

  def show
    redirect_to @story, status: :moved_permanently if request.path != story_path(@story)
  end

  def index
    @stories = policy_scope(Story)
    @stories = @stories.search(params[:search]) if params[:search]
    @stories = Kaminari.paginate_array(@stories).page(params[:page]).per(20)
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.user = current_user
    if @story.save
      redirect_to story_path(@story), notice: 'Story was successfully created.'
    else
      redirect_to new_story_path,notice: 'Error! Try again!'
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html do
          redirect_to @story, notice: 'Story was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @story.destroy
      redirect_to stories_path, notice: 'Story was successfully deleted.'
    else
      redirect_to @story
    end
  end

  def site_overview
    @stories_overview = params[:search] ? Story.all.search(params[:search]) : Story.all
    @stories_overview = Kaminari.paginate_array(@stories_overview).page(params[:page]).per(20)
  end

  private

  def set_story
    @story = Story.friendly.find(params[:id]).decorate
  end

  def authorize_actions
    authorize @story
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def story_params
    params.require(:story).permit(
      :title,
      :content,
      :tag_list,
      :search
    )
  end
end

app/views/stories/edit.html.erb
<h1>Story update</h1>
<%= form_for(@story, url: story_path(@story), html: { method: :put }) do |form| %>
  <div class="form-group">
  <%= form.label :title%>
  <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :tag_list%>
    <%= form.text_field :tag_list, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :content%>
    <%= form.text_field :content, class: "form-control" %>
  </div>
  <div class="actions">
      <%= form.submit "Submit", class: "btn btn-primary k-story-btn"%>
  </div>
<%end%>

app/views/stories/index.html.erb
<%= link_to 'Add story', new_story_path, class:" btn btn-primary k-story-btn" %>
  <div class="search-form">
    <%= form_tag(stories_path, method: :get) do %>
      <%= text_field_tag :search, params[:search], class: "search-field k-search-input" %>
      <%= submit_tag "Search", class: "btn btn-primary k-story-btn"%>
    <%end%>
    </div>
<% @stories.each do |story| %>
<div class="k-background">
  <div class="k-wrapper">
      <p><%= link_to story.title, story_path(story) %></p>
      <p><%= story.user.full_name %></p>
  </div>
</div>
<%end%>

app/views/stories/new.html.erb
<h1>New story</h1>
<%= form_for(@story, url: stories_path, html: { method: :post }) do |form| %>
  <div class="form-group">
  <%= form.label :title%>
  <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :tag_list%>
    <%= form.text_field :tag_list, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :content%>
    <%= form.text_field :content, class: "form-control" %>
  </div>
  <div class="actions">
      <%= form.submit "Submit", class: "btn btn-primary k-story-btn"%>
</div>
<%end%>

app/views/stories/show.html.erb
<div class="k-background">
  <div class="k-wrapper">
    <h1><%= @story.title%></h1>
    <h3><%= @story.user.full_name %></h3>
    <p><%= @story.content %></p>
    <p><% @story.tags.each do |tag|%>
      <%= tag.tag_name%>
      <%end%>
    </p>
    <p>Last update at <%= @story.last_update %></p>
    <% if current_user.admin? || current_user.editor? || current_user.id == @story.user.id %>
      <%= link_to "Update", edit_story_path(@story), class: "btn btn-primary k-story-btn" %>
      <% if !current_user.editor? %>
        <%= link_to "Delete", story_path(@story), method: :delete, data: {confirm: "Do you really want to delete the story?"}, class: "btn btn-primary k-story-btn" %>
      <%end%>
    <%end%>
    <%= link_to 'Back', :back, class: "btn btn-primary k-story-btn"  %>
  </div>
</div>

app/views/stories/site_overview.html.erb
<div class="search-form">
    <%= form_tag(site_overview_path, method: :get) do %>
      <%= text_field_tag :search, params[:search], class: "search-field k-search-input" %>
      <%= submit_tag "Search", class: "btn btn-primary k-story-btn"%>
    <%end%>
</div>
<% @stories_overview.each do |story| %>
<div class="k-background">
  <div class="k-wrapper">
      <p><%= link_to story.title, story_path(story) %></p>
      <p><%= story.user.full_name %></p>
  </div>
</div>
<%end%>
<div class="pagination">
  <%= paginate @stories_overview %>
  <%= link_to_next_page @stories_overview, 'Next Page' %>
</div>