config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :stories
    end
  end

  root to: 'pages#home'
  devise_for :users, controllers: { sessions: 'sessions' }
  resources :users, only: %i[edit update destroy show index] do
    get 'invite', action: :user_invite
    get 'team', action: :team
  end
  devise_scope :user do
    post '/users/invitation/new', to: 'invitations#invite_resource', as: :new_invite
  end
  resources :stories
  resources :team_presentations
  get 'site_overview', to: 'stories#site_overview', as: :site_overview
  match '/search_suggestions', to: 'search_suggestions#index', via: :get
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stories, dependent: :destroy
  before_create :set_admin, :create_slug
  before_update :create_slug
  validates :email, uniqueness: true
  enum role: %i[admin author editor]
  mount_uploader :image, ImageUploader
  # soft deleting
  acts_as_paranoid

  def create_slug
    self.slug = full_name.split(' ')[0].to_s + '-' + full_name.split(' ')[1]&.first.to_s
  end

  def set_admin
    self.role = :admin if User.count == 0
  end

  scope :pending, -> { where.not(invitation_token: true) }
  scope :accepted, -> { where.not(sign_in_count: 0) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable,
         :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         invite_for: 7.days
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  include UsersHelper

  def index; end

  def show; end

  def edit; end

  def update
    authorize current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def team
    authorize current_user
    @pending_users = User.pending.decorate
    @accepted_users = Kaminari.paginate_array(User.accepted.decorate).page(params[:page]).per(20)
    render template: 'users/team/team'
  end

  def user_invite
    @user = User.new
    authorize current_user
    render 'users/team/user_invite'
  end

  def destroy
    authorize current_user
    DeleteTeamMemberJob.perform_later(@user)
    redirect_to user_team_path(current_user)
  end

  private

  def set_user
    @user = User.find(params[:id]).decorate
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_params
    params.require(:user).permit(
      :id,
      :full_name,
      :email,
      :role,
      :bio,
      :slug,
      :password,
      :image
    )
  end
end

app/views/users/team/_invitation_status_table.html.erb
<table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Role</th>
        <th>Status</th>
        <th>Expires in</th>
      </tr>
    </thead>
    <tbody>
    <% @pending_users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td>Pending</td>
        <td><%= user.distance_of_time %></td>
      </tr>
      <%end%>
    </tbody>
  </table>

app/views/users/team/_team_members.html.erb
<table class="table table-striped">
    <thead>
      <tr>
        <th>Image</th>
        <th>Full name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Last seen</th>
      </tr>
    </thead>
    <tbody>
    <% @accepted_users.each do |user| %>
      <tr>
        <td><%= user.image %></td>
        <td><%= link_to  user.full_name , user_path(user), class: "pointer"%></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.last_sign_in %></td>
      </tr>
      <%end%>
    <%= paginate @accepted_users %>
    <%= link_to_next_page @accepted_users, 'Next Page' %>
    </tbody>
  </table>

app/views/users/team/_user_invite.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for(@user, url: new_invite_path(@user), html: { method: :post }) do |form| %>
    <%= render "devise/shared/error_messages", resource: @user %>

        <%= form.label :email%>
        <%= form.text_field :email %>
  
      <%= form.label :role%>
      <%= form.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>

    <div class="actions">
      <%= form.submit t("devise.invitations.new.submit_button")%>
    </div>
<% end %>

app/views/users/team/team.html.erb
<%= link_to 'Invite People', user_invite_path, :remote => true, class: (current_user.admin?) ? 'btn btn-primary' : 'btn btn-primary disabled'%>
<div id="user_invite">
   
</div>
<%= render 'users/team/invitation_status_table' %>
</br>
<%= render partial: 'users/team/team_members' %>

app/views/users/team/user_invite.js.erb
$("#user_invite").html("<%= escape_javascript(render partial: 'users/team/user_invite') %>");