config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :stories
    end
  end

  root to: 'pages#home'
  devise_for :users, controllers: { sessions: 'sessions' }
  resources :users, only: %i[edit update destroy show index] do
    get 'invite', action: :user_invite
    get 'team', action: :team
  end
  devise_scope :user do
    post '/users/invitation/new', to: 'invitations#invite_resource', as: :new_invite
  end
  resources :stories
  resources :team_presentations
  get 'site_overview', to: 'stories#site_overview', as: :site_overview
  match '/search_suggestions', to: 'search_suggestions#index', via: :get
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  before_create :generate_access_token

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search_suggestion.rb
class SearchSuggestion
  def self.seed
    Story.find_each do |story|
      title = story.title
      1.upto(title.length - 1) do |n|
        prefix = title[0, n]
        $redis.zadd 'search-suggestions:#{prefix.downcase}', 1, title.downcase
      end
    end
  end

  def self.terms_for(_prefix)
    $redis.zrevrange 'search-suggestions:#{prefix.downcase}', 0, 9
  end
end

app/models/story.rb
class Story < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged history]
  default_scope { order(created_at: :desc) }
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy
  validates :title, presence: true

  scope :stories_author, ->(user) { where(user_id: user.id) }
  scope :search, ->(title) { where('title like ?', "%#{title}%") }

  def tag_list
    tags.join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :stories, through: :taggings, dependent: :destroy

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :story
end

app/models/team_presentation.rb
class TeamPresentation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stories, dependent: :destroy
  before_create :set_admin, :create_slug
  before_update :create_slug
  validates :email, uniqueness: true
  enum role: %i[admin author editor]
  mount_uploader :image, ImageUploader
  # soft deleting
  acts_as_paranoid

  def create_slug
    self.slug = full_name.split(' ')[0].to_s + '-' + full_name.split(' ')[1]&.first.to_s
  end

  def set_admin
    self.role = :admin if User.count == 0
  end

  scope :pending, -> { where.not(invitation_token: true) }
  scope :accepted, -> { where.not(sign_in_count: 0) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable,
         :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         invite_for: 7.days
end

app/models/view.rb
class View < ApplicationRecord # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable # Include default devise modules. Others available are:
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name])
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < Devise::InvitationsController
  def invite_resource
    User.invite!(invite_params, current_user) do |invitable|
      invitable.update!(role: invite_params[:role])
      redirect_to user_team_path(current_user), notice: 'Invitation has been sent successfully'
    end
  end

  # this is called when accepting invitation
  # should return an instance of resource class
  def accept_resource
    resource = resource_class.accept_invitation!(update_resource_params) # Report accepting invitation to analytics
    Analytics.report('invite.accept', resource.id)
    resource
  end

  def invite_params
    params.require(:user).permit(:email, :role)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  private

  def sign_up_params
    params.require(:user).permit(
      :full_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  include StoriesHelper
  before_action :set_story, only: %i[show edit update destroy]
  before_action :authorize_actions, only: %i[edit update destroy]

  def show
    redirect_to @story, status: :moved_permanently if request.path != story_path(@story)
  end

  def index
    @stories = policy_scope(Story)
    @stories = @stories.search(params[:search]) if params[:search]
    @stories = Kaminari.paginate_array(@stories).page(params[:page]).per(20)
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.user = current_user
    if @story.save
      redirect_to story_path(@story), notice: 'Story was successfully created.'
    else
      redirect_to new_story_path,notice: 'Error! Try again!'
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html do
          redirect_to @story, notice: 'Story was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @story.destroy
      redirect_to stories_path, notice: 'Story was successfully deleted.'
    else
      redirect_to @story
    end
  end

  def site_overview
    @stories_overview = params[:search] ? Story.all.search(params[:search]) : Story.all
    @stories_overview = Kaminari.paginate_array(@stories_overview).page(params[:page]).per(20)
  end

  private

  def set_story
    @story = Story.friendly.find(params[:id]).decorate
  end

  def authorize_actions
    authorize @story
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  include UsersHelper

  def index; end

  def show; end

  def edit; end

  def update
    authorize current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def team
    authorize current_user
    @pending_users = User.pending.decorate
    @accepted_users = Kaminari.paginate_array(User.accepted.decorate).page(params[:page]).per(20)
    render template: 'users/team/team'
  end

  def user_invite
    @user = User.new
    authorize current_user
    render 'users/team/user_invite'
  end

  def destroy
    authorize current_user
    DeleteTeamMemberJob.perform_later(@user)
    redirect_to user_team_path(current_user)
  end

  private

  def set_user
    @user = User.find(params[:id]).decorate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper; end

app/helpers/pages_helper.rb
module PagesHelper; end

app/helpers/stories_helper.rb
module StoriesHelper
  def story_params
    params.require(:story).permit(
      :title,
      :content,
      :tag_list,
      :search
    )
  end
end

app/helpers/team_presentations_helper.rb
module TeamPresentationsHelper
  def team_presentation_params
    params.require(:team_presentation).permit(:title, :description)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_params
    params.require(:user).permit(
      :id,
      :full_name,
      :email,
      :role,
      :bio,
      :slug,
      :password,
      :image
    )
  end
end

app/views/layouts/_alerts.html.erb
<p class='notice'><%= notice %></p>
<p class='alert'><%= alert %></p>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-tabs topnav">
<% if user_signed_in? %>
    <li class="nav-item k-user">
     <%= current_user.email%>
    </li>
  <li class="nav-item">
  <%= active_link_to "Your profile", user_path(current_user.id), active: :exclusive, class: "nav-link"%>
  </li>
  <% if current_user.admin? %>
  <li class="nav-item">
  <%= active_link_to "Team", user_team_path(current_user), class: "nav-link"%>
  </li>
   <li class="nav-item">
  <%= active_link_to "Team presentation", team_presentations_path, class: "nav-link"%>
  </li>
  <%end%>
   <li class="nav-item">
  <%= active_link_to "Story", stories_path, class: "nav-link"  %>
  </li>
  <li class="nav-item">
  <%= active_link_to "Site overview", site_overview_path, class: "nav-link"  %>
  </li>
  <li class="nav-item">
  <%= active_link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link"  %>
  </li>
  <%else%>
  <li class="nav-item">
  <%= active_link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
  <%= active_link_to "Login", new_user_session_path, class: 'nav-link' %>
  </li>
  <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GhostJelena</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
  <div class="main-app">
    <%= render partial: 'layouts/alerts' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<p> Welcome</p>

app/views/team/_invitation_status_table.html.erb
<table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Role</th>
        <th>Status</th>
        <th>Expires in</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <% if user.invitation_token == nil || user.invitation_token == "" %>
        <td>Accepted</td>
        <td></td>
        <%else%>
        <td>Pending</td>
        <td><%= distance_of_time_in_words((user.invitation_sent_at + 7.days), Time.now)%> </td>
        <%end%>
      </tr>
      <%end%>
    </tbody>
  </table>